trigger:
- main

pool:
  vmImage: 'ubuntu-latest'

steps:
- task: Docker@2
  displayName: 'Build Docker Image'
  inputs:
    command: 'build'
    repository: 'ecommerce-app'
    dockerfile: '$(Build.SourcesDirectory)/Dockerfile'
    tags: |
      latest
      $(Build.BuildId)

- task: Docker@2
  displayName: 'Push to ACR'
  inputs:
    command: 'push'
    repository: 'ecommerce-app'
    containerRegistry: 'ACRConnection'
    tags: |
      latest
      $(Build.BuildId)

- task: CopyFiles@2
  displayName: 'Copy Artifacts (Manifests)'
  inputs:
    SourceFolder: '$(Build.SourcesDirectory)'
    Contents: '**/*.yaml'
    TargetFolder: '$(Build.ArtifactStagingDirectory)'

- task: PublishBuildArtifacts@1
  displayName: 'Publish Artifacts'
  inputs:
    PathtoPublish: '$(Build.ArtifactStagingDirectory)'
    ArtifactName: 'manifests'
